// Code generated by 'go run ./cmd/reset'. DO NOT EDIT.

package model

// Reset сбрасывает состояние PostURLHandlerResponse к нулевым значениям.
func (x *PostURLHandlerResponse) Reset() {
	if x == nil {
		return
	}

	x.ErrMsg = ""
	x.Result = ""
}

// Reset сбрасывает состояние FileStorage к нулевым значениям.
func (x *FileStorage) Reset() {
	if x == nil {
		return
	}

	x.SURL = nil
	x.Encoder = nil
}
