// Package main — утилита для генерации метода Reset() для структур с меткой // generate:reset.
//
// Использование:
//
//	go run ./cmd/reset
//
// Алгоритм:
// 1. Сканирует все пакеты начиная с корня
// 2. Для каждой структуры с комментарием // generate:reset
// 3. Генерирует метод Reset()
// 4. Сохраняет в reset.gen.go в том же пакете
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/packages"
)

// Generator управляет процессом генерации.
type Generator struct {
	fset     *token.FileSet
	packages map[string]*Package // path → Package
}

// Package содержит информацию о Go-пакете.
type Package struct {
	Name    string
	Dir     string
	Structs []*Struct
}

// Struct — структура, помеченная для генерации Reset().
type Struct struct {
	Name   string
	Fields []*Field
}

// Field — поле структуры.
type Field struct {
	Name      string
	Type      string
	IsPointer bool
	IsStruct  bool
	PkgPath   string // полный import (если внешний)
}

func main() {
	if err := run(); err != nil {
		log.Fatal(err)
	}
}

func run() error {
	g := &Generator{
		fset:     token.NewFileSet(),
		packages: make(map[string]*Package),
	}

	// ❌ Убираем filepath.Walk + parser.ParseDir
	// ✅ Загружаем через packages
	if err := g.loadPackages(); err != nil {
		return fmt.Errorf("ошибка загрузки пакетов: %w", err)
	}

	// Генерируем файлы
	for _, pkg := range g.packages {
		if len(pkg.Structs) == 0 {
			continue
		}
		if err := g.generateResetFile(pkg); err != nil {
			return err
		}
		fmt.Printf("Сгенерировано: %s/reset.gen.go (%d структур)\n", pkg.Dir, len(pkg.Structs))
	}

	fmt.Println("Генерация завершена")
	return nil
}

// loadPackages загружает все пакеты в проекте.
func (g *Generator) loadPackages() error {
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypesInfo,
		Tests: false,
	}

	// Сканируем весь модуль
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		g.processPackage(pkg)
	}
	return nil
}
func (g *Generator) processPackage(pkg *packages.Package) {
	pkgPath := filepath.Dir(pkg.GoFiles[0]) // базовая директория
	if _, exists := g.packages[pkgPath]; !exists {
		g.packages[pkgPath] = &Package{
			Name:    pkg.Name,
			Dir:     pkgPath,
			Structs: []*Struct{},
		}
	}
	current := g.packages[pkgPath]

	for _, file := range pkg.Syntax {
		f := pkg.Fset.File(file.Pos())
		if f == nil {
			continue
		}

		ast.Inspect(file, func(n ast.Node) bool {
			genDecl, ok := n.(*ast.GenDecl)
			if !ok {
				return true
			}

			// Проверяем комментарий // generate:reset
			if genDecl.Doc == nil {
				return true
			}

			hasTag := false
			for _, comment := range genDecl.Doc.List {
				if comment.Text == "// generate:reset" {
					hasTag = true
					break
				}
			}
			if !hasTag {
				return true
			}

			if genDecl.Tok != token.TYPE {
				return true
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				s := &Struct{
					Name:   typeSpec.Name.Name,
					Fields: []*Field{},
				}

				for _, field := range structType.Fields.List {
					ft := formatExpr(field.Type)
					isPtr := isPointer(field.Type)
					isStruct := isNamedStruct(field.Type, pkg.TypesInfo)

					for _, name := range field.Names {
						s.Fields = append(s.Fields, &Field{
							Name:      name.Name,
							Type:      ft,
							IsPointer: isPtr,
							IsStruct:  isStruct,
						})
					}
				}

				current.Structs = append(current.Structs, s)
				fmt.Printf(" Найдена структура для сброса: %s.%s\n", pkg.Name, s.Name)
			}

			return true
		})
	}
}

func (g *Generator) generateResetFile(pkg *Package) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by 'go run ./cmd/reset'. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg.Name + "\n\n")

	// Импорты, если понадобятся
	imports := make(map[string]bool)
	for _, s := range pkg.Structs {
		for _, f := range s.Fields {
			if f.IsStruct && !isStdlibType(f.Type, f.PkgPath) {
				pkgName := getPackageName(f.PkgPath)
				if pkgName != "" && pkgName != pkg.Name {
					imports[pkgName] = true
				}
			}
		}
	}
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for imp := range imports {
			buf.WriteString("\t_ \"" + imp + "\"\n") // заглушка, если реально не используется
		}
		buf.WriteString(")\n\n")
	}

	for _, s := range pkg.Structs {
		buf.WriteString(fmt.Sprintf("// Reset сбрасывает состояние %s к нулевым значениям.\n", s.Name))
		buf.WriteString(fmt.Sprintf("func (x *%s) Reset() {\n", s.Name))
		buf.WriteString("if x == nil { return }\n\n")

		for _, f := range s.Fields {
			var line string

			if isSlice(f.Type) {
				line = fmt.Sprintf("x.%s = x.%s[:0]", f.Name, f.Name)
			} else if isMap(f.Type) {
				line = fmt.Sprintf("clear(x.%s)", f.Name)
			} else if f.IsPointer {
				line = fmt.Sprintf("x.%s = nil", f.Name)
			} else if f.IsStruct {
				// Только если не из stdlib и есть Reset() — но пока отключим
				if !isStdlibType(f.Type, f.PkgPath) && hasResetMethod("*"+f.Type) {
					line = fmt.Sprintf("if x.%s != nil { x.%s.Reset() }", f.Name, f.Name)
				} else {
					line = fmt.Sprintf("x.%s = %s{}", f.Name, f.Type) // только если это локальная структура
				}
			} else {
				// Примитивы и интерфейсы
				line = fmt.Sprintf("x.%s = %s", f.Name, zeroValue(f.Type))
			}

			buf.WriteString(line + "\n")
		}

		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка форматирования кода: %w\n%s", err, buf.String())
	}

	outputPath := filepath.Join(pkg.Dir, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return err
	}

	fmt.Printf(" Сгенерировано: %s (%d структур)\n", outputPath, len(pkg.Structs))
	return nil
}
func getPackageName(importPath string) string {
	// Убираем версии: github.com/pkg/v3 → github.com/pkg
	importPath = removeVersionSuffix(importPath)

	// Берём последнюю часть пути
	return filepath.Base(importPath)
}

// removeVersionSuffix убирает суффиксы вроде /v2, /v3 из пути
func removeVersionSuffix(path string) string {
	for i := len(path) - 1; i > 0 && path[i] >= '0' && path[i] <= '9'; i-- {
		if path[i-1] == '/' && path[i-2] == 'v' {
			return path[:i-2]
		}
	}
	return path
}
func isStdlibType(typeName, pkgPath string) bool {
	if pkgPath == "" {
		return false
	}
	pkgName := getPackageName(pkgPath)

	stdPkgs := map[string]bool{
		"sync": true, "os": true, "database/sql": true,
		"time": true, "context": true, "net": true,
	}

	if stdPkgs[pkgName] {
		return true
	}

	// Точные имена типов
	switch typeName {
	case "sync.Mutex", "sync.RWMutex",
		"*os.File", "*os.Stdout", "*os.Stderr", "*os.Stdin",
		"*sql.DB", "*sql.Tx", "sql.NullString", "sql.driver",
		"context.Context", "context.cancelCtx", "context.timerCtx",
		"time.Time", "time.Ticker", "time.Timer":
		return true
	}

	return false
}

// hasResetMethod — заглушка. В реальном анализе используй types.Info.
// Здесь мы просто предполагаем, что если имя содержит "Struct", то Reset() может быть.
// Для точности — нужно анализировать types.Named.Methods.
func hasResetMethod(typeName string) bool {
	return false // временно отключено — безопаснее
}

func cleanTypeName(t string) string {
	if strings.HasPrefix(t, "*") {
		return t[1:]
	}
	return t
}

// Вспомогательные функции

func isVendorOrGenerated(path string) bool {
	parts := strings.Split(filepath.ToSlash(path), "/")
	for _, p := range parts {
		if p == "vendor" || p == "mocks" || p == "pb" {
			return true
		}
	}
	return false
}

func isGeneratedFile(name string) bool {
	return strings.Contains(name, "gen.go") || strings.Contains(name, "_test.go")
}

func formatExpr(expr ast.Expr) string {
	switch e := expr.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.SelectorExpr:
		return formatExpr(e.X) + "." + e.Sel.Name
	case *ast.StarExpr:
		return "*" + formatExpr(e.X)
	case *ast.ArrayType:
		if e.Len == nil {
			return "[]" + formatExpr(e.Elt)
		}
		return fmt.Sprintf("[%s]%s", e.Len, formatExpr(e.Elt))
	case *ast.MapType:
		return "map[" + formatExpr(e.Key) + "]" + formatExpr(e.Value)
	default:
		return "interface{}" // fallback
	}
}

func isPointer(expr ast.Expr) bool {
	_, ok := expr.(*ast.StarExpr)
	return ok
}

func isNamedStruct(expr ast.Expr, info *types.Info) bool {
	typ := info.TypeOf(expr)
	if typ == nil {
		return false
	}
	// Убираем указатели
	for {
		ptr, ok := typ.(*types.Pointer)
		if !ok {
			break
		}
		typ = ptr.Elem()
	}
	_, isStruct := typ.Underlying().(*types.Struct)
	return isStruct
}

func isBuiltInType(name string) bool {
	switch name {
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"float32", "float64",
		"string", "bool", "byte", "rune":
		return true
	}
	return false
}

func isSlice(expr string) bool { return strings.HasPrefix(expr, "[]") }
func isMap(expr string) bool   { return strings.HasPrefix(expr, "map[") }

func zeroValue(t string) string {
	switch {
	case isSlice(t), isMap(t):
		return t + "{}"
	case t == "string":
		return `""`
	case t == "bool":
		return "false"
	case strings.HasPrefix(t, "int") || strings.HasPrefix(t, "uint") || strings.HasPrefix(t, "float"):
		return "0"
	default:
		return t + "{}" // для структур
	}
}
