package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"os"
	"path/filepath"

	"golang.org/x/tools/go/packages"
)

// loadPackages загружает все пакеты в проекте.
func (g *Generator) loadPackages() error {
	cfg := &packages.Config{
		Mode:  packages.NeedName | packages.NeedFiles | packages.NeedSyntax | packages.NeedTypesInfo,
		Tests: false,
	}

	// Сканируем весь модуль
	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		g.processPackage(pkg)
	}
	return nil
}
func (g *Generator) processPackage(pkg *packages.Package) {
	pkgPath := filepath.Dir(pkg.GoFiles[0]) // базовая директория
	if _, exists := g.packages[pkgPath]; !exists {
		g.packages[pkgPath] = &Package{
			Name:    pkg.Name,
			Dir:     pkgPath,
			Structs: []*Struct{},
		}
	}
	current := g.packages[pkgPath]

	for _, file := range pkg.Syntax {
		f := pkg.Fset.File(file.Pos())
		if f == nil {
			continue
		}

		ast.Inspect(file, func(n ast.Node) bool {
			genDecl, ok := n.(*ast.GenDecl)
			if !ok {
				return true
			}

			// Проверяем комментарий // generate:reset
			if genDecl.Doc == nil {
				return true
			}

			hasTag := false
			for _, comment := range genDecl.Doc.List {
				if comment.Text == "// generate:reset" {
					hasTag = true
					break
				}
			}
			if !hasTag {
				return true
			}

			if genDecl.Tok != token.TYPE {
				return true
			}

			for _, spec := range genDecl.Specs {
				typeSpec, ok := spec.(*ast.TypeSpec)
				if !ok {
					continue
				}
				structType, ok := typeSpec.Type.(*ast.StructType)
				if !ok {
					continue
				}

				s := &Struct{
					Name:   typeSpec.Name.Name,
					Fields: []*Field{},
				}

				for _, field := range structType.Fields.List {
					ft := formatExpr(field.Type)
					isPtr := isPointer(field.Type)
					isStruct := isNamedStruct(field.Type, pkg.TypesInfo)

					for _, name := range field.Names {
						s.Fields = append(s.Fields, &Field{
							Name:      name.Name,
							Type:      ft,
							IsPointer: isPtr,
							IsStruct:  isStruct,
						})
					}
				}

				current.Structs = append(current.Structs, s)
				fmt.Printf(" Найдена структура для сброса: %s.%s\n", pkg.Name, s.Name)
			}

			return true
		})
	}
}

func (g *Generator) generateResetFile(pkg *Package) error {
	var buf bytes.Buffer

	buf.WriteString("// Code generated by 'go run ./cmd/reset'. DO NOT EDIT.\n\n")
	buf.WriteString("package " + pkg.Name + "\n\n")

	// Импорты, если понадобятся
	imports := make(map[string]bool)
	for _, s := range pkg.Structs {
		for _, f := range s.Fields {
			if f.IsStruct && !isStdlibType(f.Type, f.PkgPath) {
				pkgName := getPackageName(f.PkgPath)
				if pkgName != "" && pkgName != pkg.Name {
					imports[pkgName] = true
				}
			}
		}
	}
	if len(imports) > 0 {
		buf.WriteString("import (\n")
		for imp := range imports {
			buf.WriteString("\t_ \"" + imp + "\"\n") // заглушка, если реально не используется
		}
		buf.WriteString(")\n\n")
	}

	for _, s := range pkg.Structs {
		buf.WriteString(fmt.Sprintf("// Reset сбрасывает состояние %s к нулевым значениям.\n", s.Name))
		buf.WriteString(fmt.Sprintf("func (x *%s) Reset() {\n", s.Name))
		buf.WriteString("if x == nil { return }\n\n")

		for _, f := range s.Fields {
			var line string

			if isSlice(f.Type) {
				line = fmt.Sprintf("x.%s = x.%s[:0]", f.Name, f.Name)
			} else if isMap(f.Type) {
				line = fmt.Sprintf("clear(x.%s)", f.Name)
			} else if f.IsPointer {
				line = fmt.Sprintf("x.%s = nil", f.Name)
			} else if f.IsStruct {
				// Только если не из stdlib и есть Reset() — но пока отключим
				if !isStdlibType(f.Type, f.PkgPath) && hasResetMethod("*"+f.Type) {
					line = fmt.Sprintf("if x.%s != nil { x.%s.Reset() }", f.Name, f.Name)
				} else {
					line = fmt.Sprintf("x.%s = %s{}", f.Name, f.Type) // только если это локальная структура
				}
			} else {
				// Примитивы и интерфейсы
				line = fmt.Sprintf("x.%s = %s", f.Name, zeroValue(f.Type))
			}

			buf.WriteString(line + "\n")
		}

		buf.WriteString("}\n\n")
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка форматирования кода: %w\n%s", err, buf.String())
	}

	outputPath := filepath.Join(pkg.Dir, "reset.gen.go")
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		return err
	}

	fmt.Printf(" Сгенерировано: %s (%d структур)\n", outputPath, len(pkg.Structs))
	return nil
}
