package exitchecker

import (
	"go/ast"
	"strings"

	"golang.org/x/tools/go/analysis"
	"golang.org/x/tools/go/analysis/passes/inspect"
	"golang.org/x/tools/go/ast/inspector"
)

// Analyzer запрещает использование os.Exit в функции main пакета main.
var Analyzer = &analysis.Analyzer{
	Name:     "exitchecker",
	Doc:      "checks that os.Exit is not used in main.main",
	Requires: []*analysis.Analyzer{inspect.Analyzer},
	Run:      run,
}

func run(pass *analysis.Pass) (interface{}, error) {
	// Получаем инспектор для эффективного обхода
	inspect := pass.ResultOf[inspect.Analyzer].(*inspector.Inspector)

	// Фильтруем узлы: только *ast.FuncDecl
	nodeFilter := []ast.Node{
		(*ast.FuncDecl)(nil),
	}

	inspect.Preorder(nodeFilter, func(n ast.Node) {
		fn := n.(*ast.FuncDecl)

		// Проверяем: это func main()?
		if fn.Name.Name != "main" || fn.Recv != nil {
			return
		}

		// Проверяем: пакет — main?
		if pass.Pkg.Name() != "main" {
			return
		}

		// Пропускаем сгенерированные файлы
		if isGenerated(pass.Files, fn) {
			return
		}

		// Ищем вызовы: os.Exit(...)
		ast.Inspect(fn.Body, func(node ast.Node) bool {
			call, ok := node.(*ast.CallExpr)
			if !ok {
				return true
			}

			sel, ok := call.Fun.(*ast.SelectorExpr)
			if !ok {
				return true
			}

			ident, ok := sel.X.(*ast.Ident)
			if !ok {
				return true
			}

			if ident.Name == "os" && sel.Sel.Name == "Exit" {
				pass.Reportf(call.Pos(), "использование os.Exit в функции main пакета main запрещено")
			}

			return true
		})
	})

	return nil, nil
}

// isGenerated проверяет, является ли файл сгенерированным.
// Основано на комментарии: "Code generated by" или "DO NOT EDIT".
func isGenerated(files []*ast.File, fn *ast.FuncDecl) bool {
	// Находим файл, которому принадлежит функция
	var file *ast.File
	for _, f := range files {
		if f.Pos() <= fn.Pos() && fn.Pos() < f.End() {
			file = f
			break
		}
	}
	if file == nil {
		return false
	}

	// Проверяем комментарии
	for _, commentGroup := range file.Comments {
		for _, comment := range commentGroup.List {
			text := comment.Text
			// Убираем префиксы
			if strings.HasPrefix(text, "//") {
				text = strings.TrimPrefix(text, "//")
			} else if strings.HasPrefix(text, "/*") {
				text = strings.TrimPrefix(text, "/*")
				text = strings.TrimSuffix(text, "*/")
			}
			text = strings.TrimSpace(text)
			if strings.HasPrefix(text, "Code generated by") ||
				strings.Contains(text, "DO NOT EDIT") {
				return true
			}
		}
	}
	return false
}
